### PR TITLE
Swagger docs fix for enable & disable user implementation

### PR DESCRIPTION
**Pull request by Abacode7**
# Description

Please include a summary of the change. Please also include relevant trello ticket and context that might be useful for reviewer. 

# Checks:

- [ ] Unit test
- [ ] Integration test
- [ ] All tests pass on local env

### CODE REVIEW

**Comment by Abacode7** [comment]
Noticed the last PR was merged to master, any reason for that??

**Comment by danieloluwadare** [comment]
@Abacode7 .... I didn't even notice.. meaning you made your PR to master

**Comment by Abacode7** [comment]
Ooh, no issues then, this should fix it.

**Comment by danieloluwadare** [comment]
@Abacode7 Alright then

**Review by danieloluwadare — COMMENTED** [review]
Thanks for the change

**Review by danieloluwadare — APPROVED** [review]

**Pull request merged**
